python inference.py \
--data_dir /data/ephemeral/home/data/eval \
--model_dir /data/ephemeral/home/project/repo/level1-imageclassification-cv-06/best_model \
--output_dir ./ \
--age_model MyModel \
--gender_model EfficientNetb0Custom \
--mask_model MaskCustomModel \
--age_augmentation BaseAugmentation \
--gender_augmentation BaseAugmentation \
--mask_augmentation MaskAugmentation \